### ISSUE TITLE
"URL Error" on mangadex links following most recent commit

### ISSUE THREAD

**Issue by wyatt8740** [frozenpandaman/mangadex-dl#14]
Checking out the previous commit makes it work.

If I comment out the "try" part, I get the following exception instead of the vague error:
`socket.gaierror: [Errno -2] Name or service not known`

```
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/urllib3/connection.py", line 159, in _new_conn
    conn = connection.create_connection(
  File "/usr/lib/python3/dist-packages/urllib3/util/connection.py", line 61, in create_connection
    for res in socket.getaddrinfo(host, port, family, socket.SOCK_STREAM):
  File "/usr/lib/python3.8/socket.py", line 918, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
socket.gaierror: [Errno -2] Name or service not known

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 670, in urlopen
    httplib_response = self._make_request(
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 381, in _make_request
    self._validate_conn(conn)
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 978, in _validate_conn
    conn.connect()
  File "/usr/lib/python3/dist-packages/urllib3/connection.py", line 308, in connect
    conn = self._new_conn()
  File "/usr/lib/python3/dist-packages/urllib3/connection.py", line 171, in _new_conn
    raise NewConnectionError(
urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPSConnection object at 0x7f768e09ceb0>: Failed to establish a new connection: [Errno -2] Name or service not known

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/requests/adapters.py", line 439, in send
    resp = conn.urlopen(
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 724, in urlopen
    retries = retries.increment(
  File "/usr/lib/python3/dist-packages/urllib3/util/retry.py", line 439, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='mangadex.mangadex', port=443): Max retries exceeded with url: /api/manga/35451/ (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f768e09ceb0>: Failed to establish a new connection: [Errno -2] Name or service not known'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "./mangadex-dl.py", line 164, in <module>
    dl(manga_id, lang_code, url[1])
  File "./mangadex-dl.py", line 33, in dl
    r = scraper.get("https://mangadex.{}/api/manga/{}/".format(tld, manga_id))
  File "/usr/lib/python3/dist-packages/requests/sessions.py", line 543, in get
    return self.request('GET', url, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/cloudscraper-1.2.20-py3.8.egg/cloudscraper/__init__.py", line 173, in request
    super(CloudScraper, self).request(method, url, *args, **kwargs)
  File "/usr/lib/python3/dist-packages/requests/sessions.py", line 530, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/lib/python3/dist-packages/requests/sessions.py", line 643, in send
    r = adapter.send(request, **kwargs)
  File "/usr/lib/python3/dist-packages/requests/adapters.py", line 516, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPSConnectionPool(host='mangadex.mangadex', port=443): Max retries exceeded with url: /api/manga/35451/ (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f768e09ceb0>: Failed to establish a new connection: [Errno -2] Name or service not known'))
```

**Comment by matty0005** [comment]
@wyatt8740, What was the url you tried? It looks like its trying to access `mangadex.mangadex` which clearly isnt the right address.

Based on the logs, you want this URL: `https://mangadex.org/title/35451`. For me, this works

**Comment by frozenpandaman** [comment]
It's working for me as well in the latest version, i.e. as of commit a203661. What URL are you providing after the "Enter manga URL:" prompt, @wyatt8740?

**Comment by wyatt8740** [comment]
Ah, that seems to work? The full URL with the name of the manga at the end didn't but used to.

**Comment by frozenpandaman** [comment]
@wyatt8740 

>The full URL with the name of the manga at the end didn't but used to.

That still works for me?

```
$ ./mangadex-dl.py 
mangadex-dl v0.2.4
Enter manga URL: https://mangadex.org/title/21938/kani-ni-sasowarete

Title: Kani ni Sasowarete
Available chapters:
 1, 5

Enter chapter(s) to download: 
```

**Comment by frozenpandaman** [comment]
Closing since this seems (?) to be fixed now.
