### ISSUE TITLE
another mangadex update issue

### ISSUE THREAD

**Issue by orbea** [frozenpandaman/mangadex-dl#40]
mangadex-dl: 2bd20dc7135d9384f8499d585eb5eb6ab72885a6

Seems to be broken again with every series I tried.
```
$ ./mangadex-dl.py 
mangadex-dl v0.5.2
Enter manga URL or ID: https://mangadex.org/title/801513ba-a712-498c-8f57-cae55b38cc92/berserk

TITLE: Berserk
Traceback (most recent call last):
  File "/media/gittings/mangadex-dl/./mangadex-dl.py", line 275, in <module>
    dl(manga_id, lang_code, zip_up, ds)
  File "/media/gittings/mangadex-dl/./mangadex-dl.py", line 112, in dl
    for chapter in chaps["results"]:
KeyError: 'results'
```

**Comment by doroshenko** [comment]
I opened a PR that fixes this issue: https://github.com/frozenpandaman/mangadex-dl/pull/41

**Comment by frozenpandaman** [comment]
merged and fixed in the above pr :)
